import type { Metadata } from 'next'
import { Geist, Geist_Mono, Josefin_Sans } from 'next/font/google'
import './globals.css'
import './glitch.scss'
import { ThemeProvider } from '../components/theme-provider'
import { CSSProperties } from 'react'
import Placeholder from '../features/profile/placeholder'
import SectionFlat from '../components/section-flat'
import CodeReveal from '../components/code-reveal'
import Header from '../features/profile/header'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin']
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin']
})
const josefin = Josefin_Sans({
  variable: '--font-josefin',
  subsets: ['latin']
})

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html
      lang="en"
      className="dark"
      style={{ 'color-scheme': 'dark' } as CSSProperties}
    >
      <body
        className={`${josefin.variable} ${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <div className="font-josefin relative min-h-screen items-center justify-items-center">
            <Placeholder className="fixed"></Placeholder>
            <SectionFlat
              sidePattern
              className="bg-background fixed top-0 left-0 z-50 mt-2 mb-2 border-y"
            >
              <CodeReveal
                className="flex w-full justify-end border-b px-2"
                code="text-foreground font-mono text-sm font-medium"
              />
              <Header />
            </SectionFlat>
            <div className="mt-[50px]"></div>
            {children}
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
